{% set name = "flastapi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flastapi-{{ version }}.tar.gz
  sha256: 9e264258c453b030c6363e001f4e6642e3a73ed10adf6c2939fa5feb3a448c7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - flask
    # apparently package does not support pythdantic 2
    # "pydantic.errors.PydanticImportError: `pydantic.error_wrappers:ErrorWrapper` has been removed in V2."
    - pydantic <2

test:
  source_files:
    - tests
  imports:
    - flastapi
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/maarten-dp/flastapi
  summary: FastAPI-like interface plugin for Flask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
